const stopWords = new Set([
  'and',
  'the',
  'for',
  'with',
  'using',
  'based',
  'system',
  'project',
  'application',
  'app',
  'management',
  'platform',
  'portal',
  'smart',
  'automatic',
  'automated',
  'college',
  'student',
  'students',
  'engineering',
  'technology',
  'technologies',
  'science',
  'sciences',
  'design',
  'development',
  'using',
  'particular',
  'applications',
]);

export const domainKeywords = {
  ai: [
    'ai',
    'artificial',
    'intelligence',
    'machine',
    'learning',
    'deep',
    'neural',
    'ann',
    'nlp',
    'natural',
    'language',
    'vision',
    'chatbot',
    'classification',
    'prediction',
    'pattern',
    'recognition',
    'wearables',
    'neuromorphic',
  ],
  data: [
    'data',
    'analytics',
    'mining',
    'science',
    'big',
    'visualization',
    'retrieval',
    'web',
    'decision',
    'statistics',
    'probabilistic',
    'deterministic',
  ],
  algorithms: [
    'algorithm',
    'algorithms',
    'advanced',
    'structures',
    'graph',
    'combinatorics',
    'operating',
    'systems',
    'software',
    'reuse',
    'reliability',
  ],
  iot: [
    'iot',
    'internet',
    'things',
    'sensor',
    'sensors',
    'embedded',
    'microcontroller',
    'arduino',
    'raspberry',
    'edge',
    'wearables',
    'instrumentation',
  ],
  web: [
    'web',
    'website',
    'react',
    'frontend',
    'backend',
    'database',
    'fullstack',
    'full',
    'stack',
    'mobile',
    'application',
    'erp',
    'enterprise',
    'resource',
    'planning',
  ],
  cloud: [
    'cloud',
    'firebase',
    'aws',
    'azure',
    'serverless',
    'devops',
    'platform',
    'storage',
    'area',
    'networks',
    'edge',
  ],
  cybersecurity: [
    'cyber',
    'security',
    'privacy',
    'encryption',
    'cryptography',
    'authentication',
    'malware',
    'network',
    'networks',
    'blockchain',
    'law',
  ],
  robotics: ['robot', 'robotics', 'automation', 'drone', 'navigation', 'mechatronics', 'control'],
  mechanical: [
    'mechanical',
    'manufacturing',
    'machining',
    'machine',
    'mechanisms',
    'vibrations',
    'metrology',
    'measurements',
    'cim',
    'cnc',
    'cad',
    'cam',
    'cae',
    'fea',
    'finite',
    'element',
    'solid',
    'mechanics',
    'prototyping',
    'industrial',
  ],
  materials: [
    'material',
    'materials',
    'composite',
    'composites',
    'polymer',
    'polymers',
    'nanocomposites',
    'nano',
    'nanomaterials',
    'nanotechnology',
    'ceramics',
    'coatings',
    'thin',
    'films',
    'adhesives',
    'self',
    'healing',
    'semiconductors',
    'functional',
  ],
  thermal: [
    'thermal',
    'heat',
    'transfer',
    'fluid',
    'dynamics',
    'mechanics',
    'convection',
    'gas',
    'turbomachinery',
    'combustion',
    'supersonic',
    'propulsion',
    'engines',
  ],
  aerospace: [
    'aerospace',
    'aircraft',
    'propulsion',
    'turbomachinery',
    'gas',
    'dynamics',
    'combustion',
    'supersonic',
    'materials',
    'additive',
    'manufacturing',
  ],
  civil: [
    'civil',
    'rcc',
    'concrete',
    'structural',
    'structure',
    'structures',
    'masonry',
    'pavement',
    'road',
    'safety',
    'earthquake',
    'soil',
    'stabilization',
    'water',
    'resources',
    'watershed',
    'hydrological',
    'flood',
    'rainfall',
    'building',
    'steel',
    'psc',
    'shell',
  ],
  communication: [
    'communication',
    'communications',
    'wireless',
    'cellular',
    'signal',
    'antenna',
    'antennas',
    'radio',
    'mimo',
    'microwave',
    'rf',
    'optical',
    'fiber',
    'free',
    'space',
    'cognitive',
    'sdr',
    'defined',
    'networking',
  ],
  electronics: [
    'electronics',
    'electronic',
    'analog',
    'digital',
    'vlsi',
    'ic',
    'nanoelectronics',
    'low',
    'power',
    'verification',
    'processors',
    'arm',
    'embedded',
    'system',
    'systems',
    'electromagnetics',
  ],
  electrical: [
    'electrical',
    'power',
    'converter',
    'converters',
    'hvdc',
    'grid',
    'renewable',
    'energy',
    'photovoltaic',
    'ev',
    'vehicles',
    'protection',
    'quality',
    'insulating',
    'machines',
    'fault',
    'diagnosis',
    'storage',
    'batteries',
    'supercapacitors',
  ],
  control: [
    'control',
    'process',
    'fuzzy',
    'logic',
    'automation',
    'diagnosis',
    'condition',
    'monitoring',
    'reliability',
    'quality',
  ],
  biomedical: [
    'bio',
    'biomedical',
    'medical',
    'image',
    'imaging',
    'signal',
    'biosensors',
    'clinical',
    'biochemistry',
    'modality',
    'thermal',
    'microwave',
  ],
  biotechnology: [
    'biotechnology',
    'microbiology',
    'biology',
    'molecular',
    'genetic',
    'enzymology',
    'environmental',
    'computational',
    'biofuels',
    'food',
    'nutritional',
  ],
  chemistry: [
    'chemistry',
    'chemical',
    'organic',
    'inorganic',
    'synthetic',
    'coordination',
    'crystallography',
    'xray',
    'x-ray',
    'catalysis',
    'photocatalysis',
    'electrochemical',
    'membrane',
    'separation',
    'petroleum',
    'thermodynamics',
    'reaction',
    'polymers',
    'conducting',
  ],
  physics: [
    'physics',
    'nuclear',
    'condensed',
    'matter',
    'superconductivity',
    'semiconductors',
    'acoustics',
    'optical',
    'spectroscopy',
    'density',
    'functional',
    'many',
    'body',
    'simulations',
  ],
  mathematics: [
    'maths',
    'mathematics',
    'mathematical',
    'modelling',
    'algebra',
    'equations',
    'geometry',
    'riemannian',
    'calculus',
    'fractional',
    'numerical',
    'analysis',
    'methods',
    'techniques',
    'number',
    'theory',
    'ramanujan',
    'theta',
    'functions',
    'series',
    'partition',
    'automata',
    'fuzzy',
  ],
  environmental: [
    'environmental',
    'water',
    'waste',
    'pollution',
    'transport',
    'chemicals',
    'radioactivity',
    'sustainability',
    'renewable',
    'watershed',
  ],
  management: [
    'management',
    'entrepreneurship',
    'marketing',
    'organizational',
    'behavior',
    'operations',
    'research',
    'quality',
    'tqm',
    'erp',
    'decision',
    'outcome',
    'education',
    'ipr',
  ],
};

const synonymExpansions = {
  ai: ['artificial', 'intelligence', 'machine', 'learning'],
  ml: ['machine', 'learning', 'artificial', 'intelligence'],
  nlp: ['natural', 'language', 'processing'],
  iot: ['internet', 'things', 'sensor', 'embedded'],
  ev: ['electric', 'vehicles'],
  gis: ['geographic', 'remote', 'sensing'],
  rs: ['remote', 'sensing'],
  vlsi: ['integrated', 'circuit', 'electronics'],
  rf: ['radio', 'frequency', 'microwave'],
  sdr: ['software', 'defined', 'radio'],
  ajm: ['abrasive', 'jet', 'machining'],
  ecdm: ['electrochemical', 'discharge', 'machining'],
  fea: ['finite', 'element', 'analysis'],
  cad: ['computer', 'aided', 'design'],
  cam: ['computer', 'aided', 'manufacturing'],
  cae: ['computer', 'aided', 'engineering'],
  hvdc: ['high', 'voltage', 'direct', 'current'],
  rcc: ['reinforced', 'cement', 'concrete'],
  ipr: ['intellectual', 'property', 'rights'],
  erp: ['enterprise', 'resource', 'planning'],
};

export function tokenize(text = '') {
  const tokens = text
    .toLowerCase()
    .replace(/[^a-z0-9+#.\s-]/g, ' ')
    .split(/\s+/)
    .map((token) => token.trim())
    .filter((token) => token.length > 2 && !stopWords.has(token));

  const expanded = tokens.flatMap((token) => [token, ...(synonymExpansions[token] || [])]);
  return [...new Set(expanded)].filter((token) => !stopWords.has(token));
}

function detectDomains(tokens) {
  return Object.entries(domainKeywords)
    .filter(([, keywords]) => keywords.some((keyword) => tokens.has(keyword)))
    .map(([domain]) => domain);
}

export function detectTopicDomains(topic = '') {
  return detectDomains(new Set(tokenize(topic)));
}

function phraseScore(topicText, expertiseItems) {
  return expertiseItems.reduce((score, item) => {
    const normalized = item.toLowerCase();
    if (!normalized) return score;
    if (topicText.includes(normalized) || normalized.includes(topicText)) return score + 4;
    return score;
  }, 0);
}

export function keywordSimilarity(topic, faculty) {
  const normalizedTopic = topic.toLowerCase();
  const topicTokens = new Set(tokenize(topic));
  const topicDomains = detectDomains(topicTokens);

  return faculty
    .map((item) => {
      const expertiseText = [
        ...(item.expertise || []),
        item.department || '',
      ].join(' ');
      const expertiseTokens = new Set(tokenize(expertiseText));
      const expertiseDomains = detectDomains(expertiseTokens);
      const exactOverlap = [...topicTokens].filter((token) => expertiseTokens.has(token)).length;
      const fuzzyOverlap = [...topicTokens].filter(
        (token) =>
          !expertiseTokens.has(token) &&
          [...expertiseTokens].some((expertiseToken) => expertiseToken.includes(token) || token.includes(expertiseToken)),
      ).length;
      const domainOverlap = topicDomains.filter((domain) => expertiseDomains.includes(domain)).length;
      const phraseBoost = phraseScore(normalizedTopic, item.expertise || []);
      const rawScore = exactOverlap * 3 + fuzzyOverlap + domainOverlap * 2 + phraseBoost;
      const normalizedScore = topicTokens.size
        ? rawScore / (topicTokens.size * 3 + Math.max(topicDomains.length, 1) * 2)
        : 0;
      const score = Math.max(0, Math.min(1, normalizedScore));

      return {
        ...item,
        previewScore: Number(score.toFixed(4)),
        matchDebug: {
          exactOverlap,
          fuzzyOverlap,
          domainOverlap,
          phraseBoost,
        },
      };
    })
    .sort(
      (a, b) =>
        b.previewScore - a.previewScore ||
        Number(a.allocatedTeams || 0) - Number(b.allocatedTeams || 0) ||
        a.facultyName.localeCompare(b.facultyName),
    );
}
